[profile.default]
solc_version = '0.8.16'

remappings = [
    "@MT/=src/",
    "@openzeppelin/=lib/openzeppelin-contracts/contracts/"
]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config
