name: Test CI

on: push

jobs:
  build:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "16.x"

      - name: Install dependencies
        run: npm install

      - name: Unit tests
        run: npm test
